import numpy as np
import argparse
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist, PoseStamped

class MockVrpnPublisher(Node):
    def __init__(self, robot_id):
        super().__init__('mock_vrpn_publisher')
        
        # 1. Configuration: Set the static positions of the obstacles/targets
        # (x, y, yaw)
        self.stick_position = (2.0, 3.5, np.pi/4)
        self.puck_position = (6.0, 7.0, 0.0)
        
        # 2. Initial Robot Pose State (Where the robot starts on the field)
        self.robot_x = 1.0
        self.robot_y = 1.0
        self.robot_theta = 0.0
        
        # Track the incoming velocities to integrate
        self.current_v = 0.0
        self.current_w = 0.0
        
        # 3. Create publishers to mirror the VRPN Mocap topics
        self.robot_pub = self.create_publisher(PoseStamped, f'/mock/vrpn_mocap/dji_robot_{robot_id}/pose', 10)
        self.stick_pub = self.create_publisher(PoseStamped, '/mock/vrpn_mocap/hockey_sticks_1/pose', 10)
        self.puck_pub = self.create_publisher(PoseStamped, '/mock/vrpn_mocap/puck_1/pose', 10)
        
        # 4. Subscribe to the robot velocity channel to close the feedback loop
        self.create_subscription(Twist, f'/robot{robot_id}/cmd_vel', self.cmd_vel_callback, 10)
        
        # Run integration update and broadcast loop at 50 Hz
        self.dt = 0.02
        self.timer = self.create_timer(self.dt, self.simulation_step)
        self.get_logger().info("Mock VRPN Simulator active. Awaiting /robot1/cmd_vel...")

    def cmd_vel_callback(self, msg):
        # Capture the velocities generated by your controller node
        self.current_v = msg.linear.x
        self.current_w = msg.angular.z

    def simulation_step(self):
        # 5. Kinematic Unicycle Integration (Euler Method)
        # x_dot = v * cos(theta), y_dot = v * sin(theta), theta_dot = omega
        self.robot_x += self.current_v * np.cos(self.robot_theta) * self.dt
        self.robot_y += self.current_v * np.sin(self.robot_theta) * self.dt
        self.robot_theta += self.current_w * self.dt
        
        # Keep angle cleanly bounded within [-pi, pi]
        self.robot_theta = np.arctan2(np.sin(self.robot_theta), np.cos(self.robot_theta))
        
        # Time generation
        now = self.get_clock().now().to_msg()
        
        # 6. Publish Mock Robot Pose
        robot_msg = self._build_pose_msg(self.robot_x, self.robot_y, self.robot_theta, now)
        self.robot_pub.publish(robot_msg)
        
        # 7. Publish Static Target Poses
        stick_msg = self._build_pose_msg(*self.stick_position, now)
        self.stick_pub.publish(stick_msg)
        
        puck_msg = self._build_pose_msg(*self.puck_position, now)
        self.puck_pub.publish(puck_msg)

    def _build_pose_msg(self, x, y, yaw, timestamp):
        msg = PoseStamped()
        msg.header.stamp = timestamp
        msg.header.frame_id = 'map'
        msg.pose.position.x = x
        msg.pose.position.y = y
        msg.pose.position.z = 0.0
        msg.pose.orientation.x = 0.0
        msg.pose.orientation.y = 0.0
        msg.pose.orientation.z = np.sin(yaw / 2.0)
        msg.pose.orientation.w = np.cos(yaw / 2.0)
        return msg

def main(args=None):
    parser = argparse.ArgumentParser(description='Mock VRPN Publisher for Robot Simulation')
    parser.add_argument('--robot_id', type=int, default=1, help='ID of the robot to simulate')
    args, remaining = parser.parse_known_args(args)

    rclpy.init(args=remaining)
    node = MockVrpnPublisher(robot_id=args.robot_id)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()

if __name__ == '__main__':
    main()